        
namespace MAVLinkBindings {

    /// <summary>
    /// Component ids (values) for the different types and instances of onboard hardware/software that might make up a MAVLink system (autopilot, cameras, servos, GPS systems, avoidance systems etc.).
    ///       Components must use the appropriate ID in their source address when sending messages. Components can also use IDs to determine if they are the intended recipient of an incoming message. The MAV_COMP_ID_ALL value is used to indicate messages that must be processed by all components.
    ///       When creating new entries, components that can have multiple instances (e.g. cameras, servos etc.) should be allocated sequential values. An appropriate number of values should be left free after these components to allow the number of instances to be expanded.
    /// </summary>    
    public enum MAVComponentFlags {
        MavCompIdAll                         = 0,           //Target id (target_component) used to broadcast messages to all components of the receiving system. Components should attempt to process messages with this component ID and forward to components on any other interfaces. Note: This is not a valid *source* component id for a message.
        MavCompIdAutopilot1                  = 1,           //System flight controller component ("autopilot"). Only one autopilot is expected in a particular system.
        MavCompIdUser1                       = 25,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser2                       = 26,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser3                       = 27,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser4                       = 28,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser5                       = 29,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser6                       = 30,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser7                       = 31,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser8                       = 32,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser9                       = 33,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser10                      = 34,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser11                      = 35,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser12                      = 36,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser13                      = 37,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser14                      = 38,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser15                      = 39,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser16                      = 40,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser17                      = 41,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser18                      = 42,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser19                      = 43,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser20                      = 44,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser21                      = 45,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser22                      = 46,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser23                      = 47,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser24                      = 48,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser25                      = 49,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser26                      = 50,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser27                      = 51,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser28                      = 52,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser29                      = 53,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser30                      = 54,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser31                      = 55,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser32                      = 56,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser33                      = 57,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser34                      = 58,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser35                      = 59,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser36                      = 60,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser37                      = 61,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser38                      = 62,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser39                      = 63,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser40                      = 64,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser41                      = 65,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser42                      = 66,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser43                      = 67,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdTelemetryRadio              = 68,          //Telemetry radio (e.g. SiK radio, or other component that emits RADIO_STATUS messages).
        MavCompIdUser45                      = 69,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser46                      = 70,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser47                      = 71,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser48                      = 72,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser49                      = 73,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser50                      = 74,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser51                      = 75,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser52                      = 76,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser53                      = 77,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser54                      = 78,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser55                      = 79,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser56                      = 80,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser57                      = 81,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser58                      = 82,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser59                      = 83,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser60                      = 84,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser61                      = 85,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser62                      = 86,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser63                      = 87,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser64                      = 88,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser65                      = 89,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser66                      = 90,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser67                      = 91,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser68                      = 92,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser69                      = 93,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser70                      = 94,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser71                      = 95,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser72                      = 96,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser73                      = 97,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser74                      = 98,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdUser75                      = 99,          //Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network.
        MavCompIdCamera                      = 100,         //Camera #1.
        MavCompIdCamera2                     = 101,         //Camera #2.
        MavCompIdCamera3                     = 102,         //Camera #3.
        MavCompIdCamera4                     = 103,         //Camera #4.
        MavCompIdCamera5                     = 104,         //Camera #5.
        MavCompIdCamera6                     = 105,         //Camera #6.
        MavCompIdServo1                      = 140,         //Servo #1.
        MavCompIdServo2                      = 141,         //Servo #2.
        MavCompIdServo3                      = 142,         //Servo #3.
        MavCompIdServo4                      = 143,         //Servo #4.
        MavCompIdServo5                      = 144,         //Servo #5.
        MavCompIdServo6                      = 145,         //Servo #6.
        MavCompIdServo7                      = 146,         //Servo #7.
        MavCompIdServo8                      = 147,         //Servo #8.
        MavCompIdServo9                      = 148,         //Servo #9.
        MavCompIdServo10                     = 149,         //Servo #10.
        MavCompIdServo11                     = 150,         //Servo #11.
        MavCompIdServo12                     = 151,         //Servo #12.
        MavCompIdServo13                     = 152,         //Servo #13.
        MavCompIdServo14                     = 153,         //Servo #14.
        MavCompIdGimbal                      = 154,         //Gimbal #1.
        MavCompIdLog                         = 155,         //Logging component.
        MavCompIdAdsb                        = 156,         //Automatic Dependent Surveillance-Broadcast (ADS-B) component.
        MavCompIdOsd                         = 157,         //On Screen Display (OSD) devices for video links.
        MavCompIdPeripheral                  = 158,         //Generic autopilot peripheral component ID. Meant for devices that do not implement the parameter microservice.
        MavCompIdQx1Gimbal                   = 159,         //Gimbal ID for QX1.
        MavCompIdFlarm                       = 160,         //FLARM collision alert component.
        MavCompIdParachute                   = 161,         //Parachute component.
        MavCompIdGimbal2                     = 171,         //Gimbal #2.
        MavCompIdGimbal3                     = 172,         //Gimbal #3.
        MavCompIdGimbal4                     = 173,         //Gimbal #4
        MavCompIdGimbal5                     = 174,         //Gimbal #5.
        MavCompIdGimbal6                     = 175,         //Gimbal #6.
        MavCompIdBattery                     = 180,         //Battery #1.
        MavCompIdBattery2                    = 181,         //Battery #2.
        MavCompIdMavcan                      = 189,         //CAN over MAVLink client.
        MavCompIdMissionplanner              = 190,         //Component that can generate/supply a mission flight plan (e.g. GCS or developer API).
        MavCompIdOnboardComputer             = 191,         //Component that lives on the onboard computer (companion computer) and has some generic functionalities, such as settings system parameters and monitoring the status of some processes that don't directly speak mavlink and so on.
        MavCompIdOnboardComputer2            = 192,         //Component that lives on the onboard computer (companion computer) and has some generic functionalities, such as settings system parameters and monitoring the status of some processes that don't directly speak mavlink and so on.
        MavCompIdOnboardComputer3            = 193,         //Component that lives on the onboard computer (companion computer) and has some generic functionalities, such as settings system parameters and monitoring the status of some processes that don't directly speak mavlink and so on.
        MavCompIdOnboardComputer4            = 194,         //Component that lives on the onboard computer (companion computer) and has some generic functionalities, such as settings system parameters and monitoring the status of some processes that don't directly speak mavlink and so on.
        MavCompIdPathplanner                 = 195,         //Component that finds an optimal path between points based on a certain constraint (e.g. minimum snap, shortest path, cost, etc.).
        MavCompIdObstacleAvoidance           = 196,         //Component that plans a collision free path between two points.
        MavCompIdVisualInertialOdometry      = 197,         //Component that provides position estimates using VIO techniques.
        MavCompIdPairingManager              = 198,         //Component that manages pairing of vehicle and GCS.
        MavCompIdImu                         = 200,         //Inertial Measurement Unit (IMU) #1.
        MavCompIdImu2                        = 201,         //Inertial Measurement Unit (IMU) #2.
        MavCompIdImu3                        = 202,         //Inertial Measurement Unit (IMU) #3.
        MavCompIdGps                         = 220,         //GPS #1.
        MavCompIdGps2                        = 221,         //GPS #2.
        MavCompIdOdidTxrx1                   = 236,         //Open Drone ID transmitter/receiver (Bluetooth/WiFi/Internet).
        MavCompIdOdidTxrx2                   = 237,         //Open Drone ID transmitter/receiver (Bluetooth/WiFi/Internet).
        MavCompIdOdidTxrx3                   = 238,         //Open Drone ID transmitter/receiver (Bluetooth/WiFi/Internet).
        MavCompIdUdpBridge                   = 240,         //Component to bridge MAVLink to UDP (i.e. from a UART).
        MavCompIdUartBridge                  = 241,         //Component to bridge to UART (i.e. from UDP).
        MavCompIdTunnelNode                  = 242,         //Component handling TUNNEL messages (e.g. vendor specific GUI of a component).
        MavCompIdSystemControl               = 250          //Component for handling system messages (e.g. to ARM, takeoff, etc.).
    }

}
